name: Python Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar flake8
        run: pip install flake8

      - name: Ejecutar flake8
        run: flake8 gestor_tareas.py
